// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMxWeNxuKz12VCxOb4n1wzYAwD7tw6OZQ',
    appId: '1:60525522562:web:2a602c0a5afa4e8d750e9b',
    messagingSenderId: '60525522562',
    projectId: 'rungrosh-app',
    authDomain: 'rungrosh-app.firebaseapp.com',
    storageBucket: 'rungrosh-app.appspot.com',
    measurementId: 'G-NBLMFH2CGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSRWRLWbdUhIecbjyU782WiYolzr7EyJs',
    appId: '1:60525522562:android:6082c605cda21965750e9b',
    messagingSenderId: '60525522562',
    projectId: 'rungrosh-app',
    storageBucket: 'rungrosh-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqBpv7uDFKlSgn0U8S6G4PWJ9eq-nnLvM',
    appId: '1:60525522562:ios:99ceabc4c30ed50d750e9b',
    messagingSenderId: '60525522562',
    projectId: 'rungrosh-app',
    storageBucket: 'rungrosh-app.appspot.com',
    iosBundleId: 'com.example.ecomapp',
  );

}